export const GET_RECENT_POSTS_REQUEST = 'GET_RECENT_POSTS_REQUEST';
export const GET_RECENT_POSTS_SUCCESS = 'GET_RECENT_POSTS_SUCCESS';
export const GET_RECENT_POSTS_ERROR = 'GET_RECENT_POSTS_ERROR';

export const FOCUS_ON_POST = 'FOCUS_ON_POST';
export const RETURN_TO_POSTS = 'RETURN_TO_POSTS';

export const GET_SINGLE_POST = 'GET_SINGLE_POST';