export const GET_RECENT_POSTS_REQUEST = 'GET_RECENT_POSTS_REQUEST';
export const GET_RECENT_POSTS_SUCCESS = 'GET_RECENT_POSTS_SUCCESS';
export const GET_RECENT_POSTS_ERROR = 'GET_RECENT_POSTS_ERROR';

export const GET_SINGLE_POST_REQUEST = 'GET_SINGLE_POST_REQUEST';
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';
export const GET_SINGLE_POST_ERROR = 'GET_SINGLE_POST_ERROR';

export const GET_NEWSFEED_REQUEST = 'GET_NEWSFEED_REQUEST';
export const GET_NEWSFEED_SUCCESS = 'GET_NEWSFEED_SUCCESS';
export const GET_NEWSFEED_ERROR = 'GET_NEWSFEED_ERROR';